### ISSUE TITLE
endpoint.ex socket config qn

### ISSUE THREAD

**Issue by sc4224** [schneidmaster/socializer#1]
I have a question about this block of code:
```
  origin =
    case Mix.env() do
      :prod -> ["https://socializer-demo.herokuapp.com"]
      _ -> false
    end

  socket "/socket", SocializerWeb.AbsintheSocket,
    websocket: [check_origin: origin],
    longpoll: true
```

Does this socket configuration mean that websocket will result to true only in production from that origin? and longpoll is true regardless? can websocket and longpoll be true at the same time in development mode, how does that work with our graphql subscriptions?

**Comment by schneidmaster** [comment]
Hi there!

The `websocket: [check_origin: origin],` piece tells Phoenix to only permit websocket connections from `socializer-demo.herokuapp.com` in production (so you can't connect to the socket from JS running on some other website). In development, `check_origin` will be `false` meaning any origin is accepted.

The `longpoll` option is a bit different -- it tells Phoenix that if websockets are not supported in the browser (some older browsers don't support them, also some corporate networks block them) then it should fall back to periodically polling the server for updates using a standard HTTP request. This means that our GraphQL subscriptions will work even if websockets aren't available, just on a slight delay since we're periodically polling for updates instead of receiving them in real time.
