### ISSUE TITLE
Not an issue. Just a curious question.

### ISSUE THREAD

**Issue by tiotolstoy** [schneidmaster/socializer#4]
Hey Zach, first of all, great project. I want to do something similar except I want to use as little JavaScript on the frontend as possible (to create an artificial limit). What are some of the things I won't be able to accomplish with using only LiveView?

Apologies that this is not an issue. Was just curious and feel like you are in the best position to answer the question.

Thank you.

**Comment by schneidmaster** [comment]
Hi! To be honest, I have never really used LiveView beyond trivial "hello world" stuff so I don't have a great sense of its full capabilities. I would suspect that you can replicate most of the realtime functionality with LiveView, but I don't think that using GraphQL would then give you any benefit since LiveView just relies on regular Phoenix views.
